import { setElemIntersectionFactory } from "@upsetjs/bundle";
import {FileAttachment} from "npm:@observablehq/stdlib";
import {html} from "npm:htl";
import {csvParse} from "d3";


// Load collections profile data:
const original_profiles = [
  {
    key: "yul",
    title: "Yale University Library DPS (No ID) 2024-04-01",
    link: "https://guides.library.yale.edu/digitalpreservationsystem",
    terms: "CC-BY",
    description: "Only includes extensions from items not identified by DROID.",
    frequency_cutoff: 5, // Extensions with less than this many files are ignored.
    raw_data: await FileAttachment("../../data/collection-profiles/yale/YUL-not-identified-extensions-2024-04-01.csv").csv({typed: true})
  },
  {
    key: "yul-nu",
    title: "Yale University Library DPS (ID Not Unique) 2024-03-28",
    link: "https://guides.library.yale.edu/digitalpreservationsystem",
    terms: "CC-BY",
    description: "Only includes extensions with no unique identification when using DROID, e.g. multiple format ID matches.",
    frequency_cutoff: 5, // Extensions with less than this many files are ignored.
    raw_data: await FileAttachment("../../data/collection-profiles/yale/YUL-not-uniquely-identified-extensions-2024-03-28.csv").csv({typed: true})
  },
  {
    key: "kb-edepot",
    title: "KB eDepot 2014-03",
    terms: "CC-BY",
    link: "https://www.bitsgalore.org/2015/04/29/top-50-file-formats-in-the-kb-e-depot",
    raw_data: await FileAttachment("../../data/collection-profiles/kb/KB-eDepot-FExtensions-v3-2014-03.csv").csv({typed: true})
  },
  {
    key: "nara-era",
    title: "NARA ERA 2024-09-10",
    terms: "CC0 1.0 Universal",
    link: "https://github.com/usnationalarchives/digital-preservation/tree/master/File_Extensions",
    truncated_at: 6,
    description: html`NARA’s dataset is not an exact, up-to-date representation of every file extension and count in NARA’s electronic records holdings. The extensions and counts provided are generated by combining reports from various preservation systems for Federal, Legislative, and Presidential electronic records. In this dataset, extensions with a count of less than 100 have been truncated to 6 characters. Files with no extension (null values) have been excluded from this dataset. NARA will post updated versions of this dataset on GitHub: <a href="https://github.com/usnationalarchives/digital-preservation/tree/master/File_Extensions">https://github.com/usnationalarchives/digital-preservation/tree/master/File_Extensions</a>.`,
    raw_data: await FileAttachment("../../data/collection-profiles/nara/NARA-ERA-Format-Profile-2024-09-10.csv").csv({typed: true})
  },
  {
    key: "hl-drs",
    title: "Harvard Library DRS 2024-06-06",
    link: "https://preservation.library.harvard.edu/digital-preservation-repository",
    terms: "CC-BY",
    raw_data: await FileAttachment("../../data/collection-profiles/harvard/Harvard-Library-DRS-2024-06-06.csv").csv({typed: true})
  },
  {
    key: "lc-2020",
    title: "Library of Congress (extracted test set) 2020",
    link: "https://www.loc.gov/about/general-information/",
    terms: "CC-0",
    description: "This file extension profile represents an extracted test set of items and do not accurately represent the full holdings of the Library of Congress.",
    raw_data: await FileAttachment("../../data/collection-profiles/loc/LoC-2020.csv").csv({typed: true})
  },
  {
    key: "lc-2022",
    title: "Library of Congress (extracted test set) 2022",
    link: "https://www.loc.gov/about/general-information/",
    terms: "CC-0",
    description: "This file extension profile represents an extracted test set of items and do not accurately represent the full holdings of the Library of Congress.",
    raw_data: await FileAttachment("../../data/collection-profiles/loc/LoC-2022.csv").csv({typed: true})
  },
  {
    key: "lc-2024",
    title: "Library of Congress (extracted test set) 2024",
    link: "https://www.loc.gov/about/general-information/",
    terms: "CC-0",
    description: "This file extension profile represents an extracted test set of items and do not accurately represent the full holdings of the Library of Congress.",
    raw_data: await FileAttachment("../../data/collection-profiles/loc/LoC-2024.csv").csv({typed: true})
  },
  {
    key: "cul-ts-2024",
    title: "Cambridge University Library Transfer Service 2024-04",
    link: "https://www.lib.cam.ac.uk/digitalpreservation/services/transfer-service",
    terms: "CC-BY",
    raw_data: await FileAttachment("../../data/collection-profiles/cambridge/Transfer_Service_CUL_File_Extensions-2024-04.csv").csv({typed: true})
  },
  {
    key: "frdr-2024",
    title: "Digital Research Alliance of Canada FRDR 2024-03",
    link: "https://www.frdr-dfdr.ca/repo/",
    description: "The Digital Research Alliance of Canada's Federated Research Data Repository (FRDR).",
    terms: "CC-BY",
    raw_data: await FileAttachment("../../data/collection-profiles/drac/Alliance-FRDR-2024-03.csv").csv({typed: true})
  },
  {
    key: "anz-2024",
    title: "Archives New Zealand 2024-09",
    link: "https://www.archives.govt.nz/",
    description: "",
    terms: "CC-BY",
    raw_data: await FileAttachment("../../data/collection-profiles/anz/ANZ_extensions_2024-09.csv").csv({typed: true})
  },
  {
    key: "bac-lac-2024",
    title: "Library and Archives Canada 2024-09",
    link: "https://library-archives.canada.ca/",
    description: "",
    terms: "CC-BY",
    raw_data: await FileAttachment("../../data/collection-profiles/bac-lac/20240905_LAC_DPFiles_byExtensionFileCount.csv").csv({typed: true})
  },
  {
    key: "nln-2024",
    title: "The National Library of Norway 2024-10",
    link: "https://digitalpreservation-blog.nb.no/",
    description: "",
    terms: "CC-BY",
    raw_data: await FileAttachment("../../data/collection-profiles/nln/2024-10-03-NLN-extensions.csv").csv({typed: true})
  },
  {
    key: "naa-2024",
    title: "The National Archives of Australia 2024",
    link: "https://naa.gov.au",
    description: "",
    terms: "CC-BY",
    raw_data: await FileAttachment("../../data/collection-profiles/naa/naa-profile-2024.csv").csv({typed: true})
  }
]

export async function get_local_profile_folder() {
    const opfsRoot = await navigator.storage.getDirectory();
    const directoryHandle = await opfsRoot.getDirectoryHandle("collection-profiles", { create: true, });
    // Set up 'collection-profiles/ID/metadata.json'
    return directoryHandle;
}

export async function get_profiles() {
    // Copy the original list:
    const source_profiles = [];
    original_profiles.forEach((p) => source_profiles.push(p));
    // Add in local ones:
    const locals = await get_local_profile_folder();
    const entries = await locals.values();
    for await (const entry of entries) {
        if (entry.kind === 'directory') {
            console.log(`${entry.name}/`);
        } else {
            if( entry.name.endsWith('.csv')) {
                const file = await entry.getFile();
                const contents = await file.text();
                source_profiles.push({
                    key: entry.name, 
                    title: "Local profile: "+entry.name,
                    raw_data: await csvParse(contents)
                });
                console.log(`Loading ${entry.name} ${contents.slice(0,40)}`);
            }
        }
    }
    return source_profiles;
}

// Clean up the data a bit:
export function process_profile(profile, extensions_truncated_at = 100, max_extension_count = 200, count_threshold = 1) {
    profile['strange'] = [];
    profile['strange_extensions'] = [];
    profile['ok_data'] = [];
    profile['ok_data_threshold'] = [];
    profile['ok_data_all'] = [];
    profile['total_ok_count'] = 0;
    profile['total_strange_count'] = 0;
    profile['total_count'] = 0;
    const count_by_extension = {};
    profile.raw_data.forEach( function (raw_item, index) {
        // Clone original item for modification, keeping only needed bits:
        const item = {
            extension: raw_item.extension,
            count: raw_item.count,
        };
        // Ensure the count is a count:
        if( typeof item.count === 'string' || item.count instanceof String ) {
            // Is a string, might have commas in it...
            item.count = parseInt(item.count.replace(/,/g, ''));
        }
        // Check that worked, drop NaNs:
        if( isNaN(item.count) ) {
            // Nope:
            profile.strange.push(item);
            profile.strange_extensions.push(item.extension);
            return;
        }
        // Add up the total:
        profile.total_count += item.count;
        // Canonicalize the extension:
        if( item.extension == "" || item.extension == null ) {
            item.extension = "(none)";
        }
        if(  item.extension && typeof item.extension == "string" ) {
            // Start with a copy:
            var ext = item.extension;
            // Deal with special values:
            if( ext  == "(no extension)" ) {
                ext = "(none)";
            }
            // Split "bar-separated extensions" and take the first one:
            if( ext.indexOf('|') > -1 ) {
                ext = ext.slice(0, ext.indexOf('|'));
            }
            // Drop any leading dot, if present:
            ext = ext.replace(/^\.+/, '');
            // trim and downcase:
            ext = ext.trim().toLowerCase();
            // truncate if needed:
            ext = ext.slice(0, extensions_truncated_at);
            // Add a '*.' prefix if none exists:
            if( item.extension.indexOf("*") == -1 && item.extension != "(none)" && item.extension != "NULL" ) {
                item.extension = `*.${ext}`;
            } else {
                // Treat empty extensions as '(none)':
                if( item.extension == "" ) {
                    item.extension = "(none)"
                } else {
                    item.extension = ext;
                }
            }
            // Drop items that have space characters amid:
            if (item.extension.indexOf(" ") >= 0) {
                profile.strange.push(item);
                profile.strange_extensions.push(item.extension);
                profile.total_strange_count += item.count;
            } else {
                // Check if the item is already in, and use that instead if so:
                if( count_by_extension[item.extension]) {
                    count_by_extension[item.extension].count += item.count;
                } else {
                    count_by_extension[item.extension] = item;
                    profile.ok_data_all.push(item);
                }
                profile.total_ok_count += item.count;
            }
        } else {
            // Drop items that are not strings, i.e. numeric
            profile.strange.push(item);
            profile.total_strange_count += item.count;
            profile.strange_extensions.push(item.extension);
        }
    });
    // Now go through the ok_data and keep only the:
    // - count_threshold exceeding
    // - top max_extension_count
    // First sort the data by count (DESC)
    profile.ok_data_all.sort((a, b) => a.count < b.count ? 1 : -1);
    // Then slice:
    profile.ok_data_all.forEach((item, i) => {
        if( item.count >= count_threshold && i < max_extension_count ) {
            profile.ok_data.push(item);
        }
        if( item.count >= count_threshold ) {
            profile.ok_data_threshold.push(item);
        }
    });
    return profile;
}


export // Generate a plot from a profile:
function gen_profile_plot(profile, width) {
    if( ! profile ) return "";
    const profile_plot = Plot.plot({
        title: profile.title,
        subtitle: "Showing the number of files with the given file extension.",
        y: {grid: true, label: "File Count" },
        x: {grid: true, label: "Extension", tickRotate: -50 },
        color: {legend: false, label: "Registry ID", scheme: "Observable10" },
        marginBottom: 100,
        width: width,
        marks: [
            Plot.ruleY([0]),
            Plot.barY(
                profile.ok_data,
                { 
                    y: "count", 
                    x: "extension", 
                    sort: { x: "-y" },
                    tip: true,
                    fill: 1
                }
            ),
        ]
    });
    return profile_plot;
}

